#!/bin/bash

# This script generates a file that should sound like how the final output will sound

SCRIPT_DIR=$(dirname "$0")
ROOT="$SCRIPT_DIR/.."

INPUT=${1?need input}
OUTPUT=${2?need output}
SAMPLE_RATE=12787

ffmpeg -i "$INPUT" -f u8 -c:a pcm_u8 -ar "$SAMPLE_RATE" -ac 1 - |
	RAW_OUTPUT=true python "$SCRIPT_DIR/quantize_audio.py" |
	ffmpeg -f u8 -ar "$SAMPLE_RATE" -ac 1 -i - -y "$OUTPUT"
